on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Before'
        run: ls

      - uses: actions/checkout@v3

      - name: "Login to DockerHub"
        run: docker login --username USERN --password PASS

